language: haskell
branches:
  only:
  - master

before_install:
- openssl aes-256-cbc -K $encrypted_67b91d1ca19d_key -iv $encrypted_67b91d1ca19d_iv
  -in deploy-key.enc -out deploy-key -d

install: cabal install hakyll -Oo

script: bin/ci-deploy
